### ISSUE TITLE
Review coding examples in repository and google doc. 

### ISSUE THREAD

**Issue by HeshamElbashandy** [ess-dive/essdive-package-service-examples#12]
Please feel free to start reviewing the code in our Google doc and the examples repo.

Google doc link: https://docs.google.com/document/d/1WgdArPH62InCNeDsRyvj18__7JOZkVXHAbfJC8Xa3J0/edit#

**Comment by FiannaOBrien** [comment]
My experience level with Java is hopefully way lower than a user who is trying to use it. Having a lot of trouble. I'll link up and get help tomorrow.

**Comment by vchendrix** [comment]
This was tested and completed
